// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Mon May 16 22:14:19 2022

Distortion_Degree Distortion_Degree_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.rst_n(rst_n_sig) ,	// input  rst_n_sig
	.source_sop(source_sop_sig) ,	// input  source_sop_sig
	.source_eop(source_eop_sig) ,	// input  source_eop_sig
	.source_data(source_data_sig) ,	// input [23:0] source_data_sig
	.distortion_degree_numer(distortion_degree_numer_sig) ,	// output [11:0] distortion_degree_numer_sig
	.distortion_degree_denom(distortion_degree_denom_sig) ,	// output [11:0] distortion_degree_denom_sig
	.data0(data0_sig) ,	// output [23:0] data0_sig
	.data1(data1_sig) ,	// output [23:0] data1_sig
	.data2(data2_sig) ,	// output [23:0] data2_sig
	.data3(data3_sig) ,	// output [23:0] data3_sig
	.data4(data4_sig) ,	// output [23:0] data4_sig
	.data5(data5_sig) ,	// output [23:0] data5_sig
	.data6(data6_sig) ,	// output [23:0] data6_sig
	.data7(data7_sig) 	// output [23:0] data7_sig
);

