// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Sat May 07 10:30:58 2022

FFT_Ctrl FFT_Ctrl_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.rst_n(rst_n_sig) ,	// input  rst_n_sig
	.data_in(data_in_sig) ,	// input [11:0] data_in_sig
	.fft_cnt_flag(fft_cnt_flag_sig) ,	// input [31:0] fft_cnt_flag_sig
	.fft_delay_flag(fft_delay_flag_sig) ,	// input [31:0] fft_delay_flag_sig
	.source_sop_delay(source_sop_delay_sig) ,	// output  source_sop_delay_sig
	.source_eop_delay(source_eop_delay_sig) ,	// output  source_eop_delay_sig
	.source_data(source_data_sig) 	// output [23:0] source_data_sig
);

